Add basic metadata schema
mrc-ide/outpack-r pull request #1
Opened 2022-02-02 14:58 UTC by richfitz

This PR introduces a possible basic metadata schema for orderly2

The contents of `inst/schema/outpack.json` are really what I think would be most useful to get feedback on. I've done a quick check and I think this makes an acceptable common denominator for orderly. Thoughts I was never totally sure on:

* I am not 100% sure about the `time` element, either in the schema or the interface.  These are things that we track in orderly and I believe they are always things that will exist, but not totally sure.
* There are lots of ways of modelling inputs vs dependencies and I've changed my mind a few times already.  The current arrangement is an attempt to minimise how much cross checking between different parts of the schema might be needed
* The "extra" fields part is designed to take arbitrary additional data. We might force some sort of namespacing here (so require all keys to contain a dot or colon, such as `orderly:displayname`)
* The "name" field could be more flexible than the we currently have - imagining that this could include `incoming/data` as a name for example - probably reflecting an on-directory layout but perhaps not?
* The `parameters` field stands out as a little odd, but given the usefulness of filtering based on parameters as simple key-value elements I thought we might keep it here.

I've used `openssl` for the file hashing because then we can use it to sign the resulting json so that you could increase the level of trust that you have the results are unmodified (so far as you trust the originating server) without having to trust the intermediate nodes, and also so that we can use sha256 rather than md5

I've also sidestepped validating that dependencies are "real", that is that they can be found at the source location. We may want to add that later.

I've also sidestepped important details about where we store these things, and the issues around tracking where things can be found.  I am leaning towards something like:

```
.outtpack/<locationId>/<name>/<id>
```

or even just 

```
.outtpack/<locationId>/<id>
```

for the metadata store, but still noodling around with that.

There are some TODO's in the code, they're mostly just extra validation that could be done, and can be added here or later so long as we like the overall direction

2022-02-03 09:57 UTC, EmmaLRussell reviewed
Just commenting on the json schema...

So the outpack schema is intended to be a general description of what would be a report version in orderly, with just the essentials which would need to be supported by any implementation of 'orderly2'?

You don't intend to include something corresponding to a report here i.e. the code source for the task, as a name or source location? I guess that's going to differ per implementation but you'd always expect there to be something of that nature in the background?

Nothing about traceability by user - corresponding to author/requester?

How much of this schema is intended to be available before/during/after task has run? Is one of these things getting passed around before it runs, or is it all after the fact? So is Task ID just a UID that can get assigned at any time? (I'd been thinking of it like report version id but maybe it's more like the running key).

Does a task necessarily know all of its outputs before it runs? (I think we talked about this possibility before, that outputs might depend on data encountered while running.) In which case, might dependencies be more of a pattern defining a group of files rather than a single known file? Maybe not, if this is all post hoc (as seems to be suggested by inclusion of hashes and file sizes).

2022-02-03 09:57 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +                        "description": "The name of the upstream packet",
Is  a packet the same thing as a task?

2022-02-03 09:57 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +                    "files": {
So these are the output files of the dependency that this packet depends on?

2022-02-03 09:57 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +                "properties": {
I was expecting to see 'name' in here, and for that to correspond to 'source' in dependencies for packets for which this might be a dependency. But maybe I'm misunderstanding what's going on.

2022-02-03 09:57 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +        "session": {
Not really sure what session actually means in this context. Is this information about how/where the task was run e.g. what worker, running key?

2022-02-03 09:57 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +                                "size": {
Size and hash won't be known before the dependency runs - is that ok?

2022-02-03 10:08 UTC, r-ash requested changes
Couple of small things noticed in json but looks good.

What I'm not sure about is how this is going to provide the tracking you mention in orderly2 README. Where is info about where this artifact was computed, it's canonical location or where dependencies are fetched from? (maybe this is coming later too?)

Is this going to replace the run rds? Or do we still have use for that?

Where is this going to fit in orderly?

1. User starts report running `orderly_run` or `orderly_run_remote` or via web interface
2. orderly runs report (as currently does) saving output to drafts
3. orderly generates outpack for the report run to some location
4. User commits report
5. orderly moves report output from drafts to archive & does something with this outpack?

Or maybe only created on commit?
Also wondering how this will be used when a user runs `orderly_pull_archive` or `orderly_pull_dependencies` will we change those functions to read all info from the outpack for that report which is stored on the server?

2022-02-03 10:08 UTC, r-ash commented on R/metadata.R
> +outpack_metadata_depends <- function(name, id, files) {
This needs to be exported?

2022-02-03 10:08 UTC, r-ash commented on inst/schema/outpack.json
> +        }
This is missing a "type" or are you going to expand that later?

2022-02-03 10:08 UTC, r-ash commented on inst/schema/outpack.json
> +    "required": ["schemaVersion", "id", "name", "time", "outputs"]
"session" isn't required?

2022-02-03 10:08 UTC, r-ash commented on inst/schema/outpack.json
> +{
No "extra" filed in the schema which you mention in your comments. Though maybe it's not needed if the structure if completely arbitrary?

2022-02-03 10:15 UTC, richfitz commented on inst/schema/outpack.json
> +                        "description": "The name of the upstream packet",
I should document this - I've grabbed that name as one that might not suffer too much overloading. A packet will be the report or task _after it has been run_. We could call this an archive or something, but we use that in other places so was fishing for something else.

I think that a "task" or "report" will probably end up referring within orderly as something that before it runs, and perhaps packet once it has been run.  But open to thoughts and suggestions here...

2022-02-03 10:16 UTC, richfitz commented on inst/schema/outpack.json
> +                    "files": {
Yes, though unlike orderly they may be any file found within that packet (orderly will enforce that they are artefacts, but other people have found that depending directly on inputs is a potentially useful thing too)

2022-02-03 10:18 UTC, richfitz commented on inst/schema/outpack.json
> +                "properties": {
This is a list of files, so `path` is the filename; that's what is depended on. In orderly we have `artefacts` as a grouping layer around output files, but we're not enforcing this here. I'm not seeing how you expect `name` here though, which suggests something is poorly documented/explained somewhere - can you expand?

2022-02-03 10:20 UTC, richfitz commented on inst/schema/outpack.json
> +        "session": {
So, this is something I am not at all set on.

Every piece of run work will have some session information, but that will depend pretty strongly on the engine that runs it. The type of output that a standalone executable might produce, or that orderly might produce, or some python program, will all be quite different - but they'll all exist.  So I thought that we might require some information here but basically be agnostic about the structure. That has some issues with reflecting it, but we don't actually do that yet anyway for the corresponding data in orderly

2022-02-03 10:21 UTC, richfitz commented on inst/schema/outpack.json
> +                                "size": {
Yeah, I should have been clearer on this - everything here is applied _after_ the run has completed (basically as a sign-off), and orderly would bring its own runner and do things like ensure that the hash of inputs don't change during a run. We'll put reusable parts of this into outpack, but this is one of the places that flexibility feels like it would be useful

2022-02-03 10:24 UTC, richfitz commented on inst/schema/outpack.json
> +        }
See comment I've just written here on Emma's comments: https://github.com/mrc-ide/outpack/pull/1#discussion_r798391855

2022-02-03 10:25 UTC, richfitz commented on inst/schema/outpack.json
> +    "required": ["schemaVersion", "id", "name", "time", "outputs"]
also `depends` and `inputs`...

2022-02-03 10:25 UTC, EmmaLRussell commented on inst/schema/outpack.json
> +                "properties": {
I was wondering where 'source' in depends/files comes from - it's described as 'The name of the source file, within the upstream packet', so I was expecting there to be some descriptive name in an output file (corresponding to this, for an input dependency file).

2022-02-03 10:26 UTC, richfitz commented on inst/schema/outpack.json
> +{
See the implementation - extra fields come in as they are. What we might do is enforce some naming scheme on the extra fields (e.g., must require `.` or `:` as a pseudo-namespace)

2022-02-03 10:43 UTC, richfitz commented
Comments on @EmmaLRussell's comments:

Just commenting on the json schema...

> So the outpack schema is intended to be a general description of what would be a report version in orderly, with just the essentials which would need to be supported by any implementation of 'orderly2'?

Yes - this is the minimum set of values that must be provided

> You don't intend to include something corresponding to a report here i.e. the code source for the task, as a name or source location? I guess that's going to differ per implementation but you'd always expect there to be something of that nature in the background?

It is expected that at `path` there will be a directory with all this stuff, and `name` will be related to the directory (but possibly resolved by the underlying implemenation).  So for orderly/orderly2 we'll have concrete outputs in `archive/<name>/<id>` which will be passed as `path` here when running things.  But for other engines it might be useful useful to have more structure to the reports that have been run.

> Nothing about traceability by user - corresponding to author/requester?

This has not turned out to be useful in practice!  But when we migrate things we'll pull those over as `orderly.author`/`orderly.requested`

> How much of this schema is intended to be available before/during/after task has run? Is one of these things getting passed around before it runs, or is it all after the fact? So is Task ID just a UID that can get assigned at any time? (I'd been thinking of it like report version id but maybe it's more like the running key).

Everything here is post task run - most likely we'll need a few primatives for during task run.  Examples include:

* collect a set of hashes to confirm that files have not changed (orderly does this already)
* dynamic inclusion of dependencies (so copy things over, and record somewhere the dependencies are being used)
* dynamic description of outputs (see below)

> Does a task necessarily know all of its outputs before it runs? (I think we talked about this possibility before, that outputs might depend on data encountered while running.) In which case, might dependencies be more of a pattern defining a group of files rather than a single known file? Maybe not, if this is all post hoc (as seems to be suggested by inclusion of hashes and file sizes).

At the point where the metadata is written this will be known, but in the general case it won't be needed before the runs.

2022-02-03 10:48 UTC, richfitz commented
Comments on @r-ash's comments

Couple of small things noticed in json but looks good.

> What I'm not sure about is how this is going to provide the tracking you mention in orderly2 README. Where is info about where this artifact was computed, it's canonical location or where dependencies are fetched from? (maybe this is coming later too?)

This is going to be added on top; the schema here captures the things that would hold independent of that.

> Is this going to replace the run rds? Or do we still have use for that?

Run ids being the orderly ones? We'll keep those I think as they've been useful and noone objects to the format (see the regex in the schema).

> Where is this going to fit in orderly?
> 1. User starts report running orderly_run or orderly_run_remote or via web interface
> 2. orderly runs report (as currently does) saving output to drafts
> 3. orderly generates outpack for the report run to some location
> 4. User commits report
> 5. orderly moves report output from drafts to archive & does something with this outpack?
> 6. Or maybe only created on commit?

This will become a dependency of orderly - we'll use it to pick up most of the low level running and hashing eventually.  This metadata happens at your step 3, yes, replacing orderly_run.rds really

> Also wondering how this will be used when a user runs orderly_pull_archive or orderly_pull_dependencies will we change those functions to read all info from the outpack for that report which is stored on the server?

Not totally sure what you're asking here, but the remote interface will end up being built on this new format yes - nothing we need there is broader than the things currently captured in this metadata subset (name, id, parameters, really - date might also be useful, we get a manifest of files etc).

2022-02-21 10:57 UTC, hillalex commented
I still haven't quite understood the relationship between this minimal set of metadata and the full metadata desired for orderly2 (canonical location etc.) Is the idea that this schema will get expanded when the details of those trickier bits are worked out, or is there an envisioned use case for a more pared down metadata format as seen here?

2022-02-21 11:24 UTC, richfitz commented
Does https://github.com/vimc/orderly2/blob/main/structure.md help with that?

2022-03-10 15:24 UTC, closed without merging