mrc-3516 change config to add file store
mrc-ide/outpack-r pull request #22
Opened 2022-08-11 16:52 UTC by hillalex

2022-08-15 09:08 UTC, richfitz requested changes

2022-08-15 09:08 UTC, richfitz commented on R/root.R
> +    add_file_store = function() {
This is I think related to the validation problem (mrc-3052) - if a file is missing or modified here we'll fail and we'll end up with an inconsistent store (a test to verify the behaviour here would be good). Race conditions mean that doing validation-then-import is probably not ideal but it's likely there will be some shared logic.

Probably a reasonable way for this to work would be to *try* and import a packet from its unpacked data and then if that fails see if we can reconstruct it from other files we have kicking about. So if the user has deleted the file data.csv used as an input but we have other copies of that that *are* ok we should just stick one of those in the store. We might already have an equivalent file in the store. When looking through the VIMC and covid stores, there are many duplicated files due to rerunning of reports with the same inputs, and the way that outputs become inputs.

2022-08-15 09:08 UTC, richfitz commented on R/root.R
> +      invisible(lapply(self$index()$metadata, function(meta) {
This is going to loop over all packets that the current repo knows about at all, not the ones that are unpacked - we only want the latter. See `index$unpacked$packet` for a list of ids that we should consider

2022-08-15 09:08 UTC, richfitz commented on R/config.R
> +  if (value) {
This probably wants to be in tryCatch so that if it fails we don't add half a store?

2022-08-15 09:08 UTC, richfitz commented on R/root.R
> +        file_import_store(self, src, meta$files$path, meta$files$hash)
Given the behaviour of `file_import_store` we should filter this down to hashes we don't yet know about. Alternatively, change `file_import_store` to do an "if not exists" check, which is probably tidier...

2022-08-15 11:33 UTC, hillalex commented on R/root.R
> +        file_import_store(self, src, meta$files$path, meta$files$hash)
There's already an if not exists check in the file store `put` method: https://github.com/mrc-ide/outpack/blob/main/R/store.R#L50

2022-08-15 13:42 UTC, hillalex commented on R/root.R
> +    add_file_store = function() {
Looks like there is already a function to look up paths from hashes, so using that: https://github.com/mrc-ide/outpack/pull/22/commits/fa0e0323bd8b35da288dcb0e69bd2671b8e3e2ea

2022-08-16 11:50 UTC, richfitz approved these changes

2022-08-16 11:50 UTC, merged