mrc-3028
mrc-ide/outpack-r pull request #29
Opened 2022-09-06 10:23 UTC by hillalex

2022-09-06 10:51 UTC, hillalex commented on R/location.R
> +    root$index(refresh = TRUE)
is this the way to do this?

2022-09-06 13:50 UTC, richfitz requested changes
I am not sure about the deletion vs orphan difference - something to discuss perhaps? Doesn't need to be done here but I think that deletion does make some sense if we can do it because once we can no longer pull or interact with the packets we might want to be able to remove them.

Another way of doing this would be to have some sort of housekeeping "delete orphans" function that we can call later?

2022-09-06 13:50 UTC, richfitz commented on R/location.R
> +    root$index(refresh = TRUE)
yeah, the workflow here is not really obvious yet, I think that most times we load the index there's a refresh anyway, but at some point we should look at this holistically and make sure it's always done when we expect it to be done

2022-09-06 13:50 UTC, richfitz commented on R/location.R
> +    mark_packets_orphaned(id, packets, orphan_id, root)
This should only orphan packets that are *only* found at the removed location, but I think this is orphaning any packets that are found there, even if they are also found elsewhere.

So imagine we've pulled packages from production but also some test server. We remove the test server and we should be orphaning (or removing) only the packages found only from the test server

2022-09-06 13:50 UTC, richfitz commented on R/location.R
> +    orphan_id <- config$location$id[match("orphan", config$location$name)]
lookup_location_id here

2022-09-06 13:50 UTC, richfitz commented on R/location.R
> +  root$config <- config_read(root$path)
We must do this pattern (write then read) a few places - might be worth pulling it into a small function in config.R (config_update <- function(config, root) {
  config_write(config, root$path)
  root$config <- config_read(root$path)
  })

or a similar method on the root object?

2022-09-07 16:32 UTC, hillalex commented on R/location.R
> +    orphan_id <- config$location$id[match("orphan", config$location$name)]
at this point `root$config` might not have a newly created orphan location

2022-09-08 08:44 UTC, richfitz approved these changes

2022-09-08 08:44 UTC, merged