Mrc 3112 minor
mrc-ide/outpack-r pull request #34
Opened 2022-11-01 16:51 UTC by hillalex

2022-11-01 17:18 UTC, hillalex commented on R/root.R
> +    index_data = list(),
making this consistent with line 111 below, where if skipping the cache an empty list is used rather than a null

2022-11-01 17:20 UTC, hillalex commented on benchmark.Rmd
> +---
I guess this would be useful to keep, but maybe in a separate repo? Run against different commits?

2022-11-01 17:21 UTC, hillalex commented on tests/testthat/helper-server.R
> +    getNamespace("remotes")$install_github("mrc-ide/outpack.server@mrc-3112",
Complementary PR for `orderly.server`, which will only pass once this branch is merged: https://github.com/mrc-ide/outpack.server/pull/4

2022-11-02 10:09 UTC, richfitz commented on benchmark.Rmd
> +---
Good question - we've not checked for things like performance regression before, but probably worth thinking about

2022-11-02 10:13 UTC, richfitz requested changes

2022-11-02 10:13 UTC, richfitz commented on benchmark.Rmd
> +---
Can you pop this in a directory rather than the top level, and add it to .Rbuildignore, then add a comment somewhere in benchmark.Rmd about where to find the montagu-reports example repo.

2022-11-02 10:13 UTC, richfitz commented on benchmark.Rmd
> +library(dplyr)
dplyr is unused here?

2022-11-02 10:13 UTC, richfitz commented on benchmark.Rmd
> +knitr::opts_chunk$set(warning = FALSE, message = FALSE)
`error = FALSE` well worth adding here or knitr just continues after error, annoyingly just continues after error

2022-11-02 10:13 UTC, richfitz commented
Also, as you're changing behaviour, it will be best to bump the version number as then in outpack.server you can update the required version

2022-11-02 11:53 UTC, richfitz approved these changes

2022-11-02 16:19 UTC, merged