Import metadata from a file location
mrc-ide/outpack-r pull request #4
Opened 2022-03-17 15:45 UTC by richfitz

This PR adds the ability to pull metadata from one or more locations.  I've set this up using a "file location" object, roughly the same as [`orderly::orderly_remote_path`](https://www.vaccineimpact.org/orderly/reference/orderly_remote_path.html) and the same sort of idea.

No support yet for pulling actual data from one location to another, which obscures a missing concept of the index needing to know which packets it actually has.  This is quite subtle, particularly in the case of when people use the normal file store.

Also no support for any sensible querying (that will wait until after the data pull is done) so this is quite annoying to test.

The function `outpack_location_pull_metadata` is the one that the users will use - there is no analogue to this in orderly.

I had to rip out the support for `index_update` taking a vector of locations as an arg as that could leave things inconsistent.

2022-03-18 10:36 UTC, r-ash reviewed
Couple of comments about some areas I found confusing but otherwise looks good. Tests look good.

2022-03-18 10:36 UTC, r-ash commented on R/location.R
> +  index <- root$index_update()
We do an `index_update` here and in `driver$list` and in `driver$metadata`. We could drop this call?

2022-03-18 10:36 UTC, r-ash commented on R/location.R
> +  index <- root$index_update()
Oh maybe not because we need a handle on the data. Does it change in between each of these calls?

2022-03-18 10:36 UTC, r-ash commented on R/location_path.R
> +outpack_location_path <- R6::R6Class(
I think it would helpful to include some docs on this object, and on `root` object about what the functions do. I know you're not a fan of documenting internal functions but I find it quite hard to remember what these objects do and are for. Having a couple of lines to explain what these functions achieve and what `index_update` does would make it easier to remember and easier to think about these separate objects as units.

2022-03-18 10:37 UTC, richfitz commented on R/location.R
> +  index <- root$index_update()
index_update is currently the only public way to get the index out of the root. It should be cheap though

2022-03-18 12:33 UTC, r-ash requested changes
Thanks for talking me through this, got your own comments for you :smile:

2022-03-18 12:33 UTC, r-ash commented on tests/testthat/test-location.R
> +  for (name in c("x", "y", "z")) {
Could add a test for a structure like A pulling B pulling from C. In that case does A have any knowledge of C existing?

2022-03-18 12:33 UTC, r-ash commented on R/location.R
> +  for (name in setdiff(location, c("local", "orphan"))) {
(This is your own comment :)) maybe we should put these hard coded special collections into a globals or helper function. Particularly if they will be referred to elsewhere in future.

2022-03-21 09:36 UTC, r-ash approved these changes

2022-03-21 11:05 UTC, hillalex reviewed
Some thoughts about naming; like Rob I find it a little hard to keep track of what various properties are, and I wonder if there are ways to make them a little more perspicuous.

2022-03-21 11:05 UTC, hillalex commented on R/location.R
> +  known <- index$location$id[index$location$location == name]
I find it a bit confusing how `index$location` is a collection of packets with location info, I keep having to refer back to the root class to figure out what's going on. I would expect `index$location$id` to refer to location ids, rather than packet ids. Not totally sure what to suggest, but maybe `id` -> `packet`? That's sort of the analogue of the pattern we've used in relational databases (id as primary key, entity name as foreign key to that id in another table)

2022-03-21 11:05 UTC, hillalex commented on R/location.R
> +  known <- index$location$id[index$location$location == name]
Similarly if `index$index` was `index$packet`, `index$packet$id` feels clearer than `index$index$id`?

2022-03-21 11:05 UTC, hillalex commented on R/location.R
> +  dat <- driver$list()
Perhaps this comment could be subsumed into a more descriptive variable name?

2022-03-21 12:56 UTC, richfitz commented on R/location.R
> +  known <- index$location$id[index$location$location == name]
Turns out `index$index` is not (yet) needed and I've deleted it. Made the change to `location$packet`

2022-03-21 14:17 UTC, hillalex approved these changes

2022-03-21 14:47 UTC, merged