mrc-4080: Add ability to use subquery in outpack_search
mrc-ide/outpack-r pull request #40
Opened 2023-03-17 10:38 UTC by r-ash

This PR will
* Add an arg `subquery` to `outpack_search` which takes a named list of subqueries which can be referenced by name in the `expr`

Couple of things here
* The subquery I wanted to take `expr` and `scope` as say in the orderly yaml we have something like
```
depends:
  - name: B
    id: latest()
    as: report_b
  - name: A
    id: latest(usedby(report_b))
```
then when locating B we search with

```
outpack_query(id = "latest()", scope = quote(name == "B"))
```

so when we search for A we do this as
```
outpack_query(
  id = "latest(usedby(report_b))",
  scope = quote(name == "A"),
  subquery = list(
    report_b = list(expr = quote(latest()), scope = quote(name == "B"))
  )
)  
``` 
i.e. the same query as we used for getting `B`
* This adds a `none()` term. When a search returns no results we return NA_character_. If the subquery has no results then we want to substitute in some value which represents no items returned

2023-03-17 11:08 UTC, richfitz requested changes

2023-03-17 11:08 UTC, richfitz commented on R/query.R
> +    subquery_env <- as.environment(subquery)
`parent = emptyenv()` on this call, probably clearer in an if/else

2023-03-17 11:08 UTC, richfitz commented on R/query.R
> +    assert_named(subquery)
```suggestion
    assert_named(subquery, unique = TRUE)
```

2023-03-17 11:08 UTC, richfitz commented on tests/testthat/test-query.R
> +})
Add some tests on invalid use of subqueries, for example

```r
  outpack_query(quote(latest(sub == TRUE)),
                subquery = list(sub = list(expr = quote(name == "x"))),
                root = root)  
```

2023-03-17 11:08 UTC, richfitz commented on tests/testthat/test-query.R
> +})
```suggestion
  expect_equal(
    outpack_query(quote(sub),
                  subquery = list(sub = list(expr = quote(latest(name == "x")))),
                  root = root),
    x2)
})
```

2023-03-17 11:08 UTC, richfitz commented on R/query.R
> +query_parse_subquery <- function(expr, context, subquery_env, root) {
Let's not evaluate subqueries at this point, so don't pass root around. Ideally root is not needed during parse, because parse stage is just the validation the query makes sense in the abstract.

Then later evaluate the subqueries in a lazy way (like you do here)

2023-03-17 11:08 UTC, richfitz commented on R/query.R
> +is_outpack_query_evaluated <- function(x) {
Probably can just look to see if result is null or not

2023-03-17 11:08 UTC, richfitz commented on R/query.R
> +  ids <- if (is_outpack_query_evaluated(subquery)) {
A useful pattern for this:

```
if (is.null(subquery$result)) {
 subquery$result <- evaluate(whatever)
}
subquery$result
```

2023-03-17 11:23 UTC, r-ash commented on R/query.R
> +    subquery_env <- as.environment(subquery)
From docs looks like as.environment sets parent as emptyenv already

"If it is a list, the equivalent of [list2env](http://127.0.0.1:38065/help/library/base/help/list2env)(x, parent = emptyenv()) is returned."

2023-03-20 14:57 UTC, r-ash commented on tests/testthat/test-query.R
> +           "  - within           latest(parameter:a == this:x)"),
Noticed this was printing so have tidied this up here

```
Did not find 'x' within given pars ('a')
- while evaluating NULL
```

2023-03-20 15:21 UTC, r-ash commented on R/query.R
> +query_parse <- function(expr, context, subquery_env) {
We want `context` here now too because we call this from `query_parse_subquery` when we encounter a subquery we parse it but want to retain the full context for any error messages. So that if we do something like

```
outpack_query(quote(latest({sub})), root = root)
```

we get the error
```
Cannot locate subquery named 'sub'. No subqueries provided.
  - in     {sub}
  - within latest({sub})
```

2023-03-20 15:50 UTC, r-ash commented
Not sure why codefactor is failing here, lintr passes locally but for some reason it is now warning about all TODO comments (plus things in excluded testthat.R file) have you seen this before?

2023-03-24 14:43 UTC, richfitz reviewed
Thanks - couple of minor comments here, and then we can merge this

2023-03-24 14:43 UTC, richfitz commented on R/query.R
> +        available_queries <- paste0(
possibly for later, we're going to get odd errors back here where the user does use an anonymous query

2023-03-24 14:43 UTC, richfitz commented on R/query.R
> +    query_name <- ids::adjective_animal()
what do you think about instead hashing the query and returning the hash? that would then be deterministic

2023-03-24 14:43 UTC, richfitz commented on R/query_deparse.R
> +  infix_operators <- list("!", "&&", "||", "==", "!=", "<", "<=", ">", ">=",
`!` is prefix surely?

2023-03-24 14:43 UTC, richfitz commented on R/query_deparse.R
> +  infix_operators <- list("!", "&&", "||", "==", "!=", "<", "<=", ">", ">=",
I also think you have more in here than needed, you only need things from `query_functions` defined above?

2023-03-24 14:43 UTC, richfitz commented on R/query_deparse.R
> +    }
```suggestion
    sep <- if (fn == ":") "" else " "
```

2023-03-24 15:07 UTC, r-ash commented on R/query_deparse.R
> +  infix_operators <- list("!", "&&", "||", "==", "!=", "<", "<=", ">", ">=",
Oh yeah, maybe will just call this `operators`. There are additional operators here because if we don't include them errors are harder to interpret. e.g.

```
query_parse(quote(latest(a %in% b)), NULL, emptyenv())
```

Would error with message
```
Error: Invalid query '%in%(a, b)'; unknown query component '%in%'
  - in %in%(a, b)
  - within latest(%in%(a, b))
```

2023-03-24 15:12 UTC, richfitz commented on R/query_deparse.R
> +  infix_operators <- list("!", "&&", "||", "==", "!=", "<", "<=", ">", ">=",
oh, that's really nasty sorry. Perhaps there's a better way of doing this...

2023-03-24 15:19 UTC, r-ash commented on R/query_deparse.R
> +  infix_operators <- list("!", "&&", "||", "==", "!=", "<", "<=", ">", ">=",
Thanks I've split up the infix and prefix operators now

2023-03-24 15:20 UTC, r-ash commented on R/query.R
> +    query_name <- ids::adjective_animal()
Yeah nice!

2023-03-24 16:02 UTC, r-ash commented on R/query.R
> +        available_queries <- paste0(
Have pushed a test and fix for that

2023-03-24 16:35 UTC, richfitz approved these changes

2023-03-24 16:35 UTC, merged