mrc-4102: Add ability to outpack_query to search for packets which are used by another
mrc-ide/outpack-r pull request #41
Opened 2023-03-21 12:33 UTC by r-ash

This PR will
* Add a function `usedby` to `outpack_query` which takes an `id` and a second arg `immediate` which is FALSE by default
   * If 0 ids returned passed to `usedby` this returns an empty vector
   * If more than 1 id passed to `usedby` we error and prompt user to wrap expression inside `usedby` in a call to `latest`
   * If `immediate` is TRUE then only looks for immediate dependencies i.e. it does not recurse through the list

One thing here is that building the list of dependencies recursively does not check for cycles. This is because these are concrete realisations of reports. I think it is impossible for a cycle of dependencies to be created as one packet is created after another and cannot use a packet which is yet to exist. So I don't think any cycles should occur, however perhaps I should deal with the case there is a cycle anyway? For if someone has done something weird to their archive.

This PR is into mrc-4080, and should be merged into main after that.

2023-03-27 10:15 UTC, richfitz requested changes

2023-03-27 10:15 UTC, richfitz commented on R/query.R
> +query_parse_usedby <- function(expr, context, subquery_env) {
do we want to allow named args here? (so `usedby({subquery}, immediate = TRUE)`?). Another way of doing this would be to have an integer `depth` argument that allowed control of depth (so `depth = 0` is `immediate = TRUE` and `depth = Inf` is `immediate = FALSE`)

2023-03-27 10:15 UTC, richfitz commented on R/query.R
> +                     "with 1 id. Try wrapping enclosed query in 'latest' ",
```suggestion
                     "with a single id. Try wrapping enclosed query in 'latest' ",
```

2023-03-27 10:15 UTC, richfitz commented on R/query.R
> +  if (len > 1) {
Can we work this out statically? (i.e., during the parse rather than eval phase, in a way that always holds) I think we discussed that at this point there are only three things that are valid

* a single id
* a query with latest()
* a query with only()

Leaving the failure to runtime makes things a bit less predictable as things work fine at first and then fail once the system is more complex

2023-03-27 10:15 UTC, richfitz commented on R/query_index.R
> +      deps <- deps[deps %in% self$index$id] ## filter on current index
Is this not

```suggestion
      deps <- intersect(deps, self$index$id)
```

which is them simple enough to write

```suggestion
      intersect(deps, self$index$id) %||% character(0)
```

2023-03-27 16:01 UTC, r-ash commented on R/query.R
> +query_parse_usedby <- function(expr, context, subquery_env) {
Yeah sounds good, switched this for `depth` and checked that we can call it with the name. Though used `depth = 1` to mean `immediate = TRUE` which I only realised is different to proposal here after implementing that. Felt more intuitive to me that `depth = 1` will search 1 level deep (i.e. immediate parents). I think that is how e.g. mockery::stub is working? But happy to change that if you think more common to start at `depth = 0`

2023-03-27 16:01 UTC, r-ash commented on R/query.R
> +  if (len > 1) {
Yeah that makes a lot of sense, I've moved this check into the parsing step

2023-03-29 15:12 UTC, richfitz requested changes
looking good - just the literal id needed I think

2023-03-29 15:12 UTC, richfitz commented on R/query.R
> +query_parse_usedby <- function(expr, context, subquery_env) {
I feel like depth = 1 means "one child", if you're ok with that change?

2023-03-29 15:12 UTC, richfitz commented on R/query.R
> +        paste0("`depth` argument in usedby() must be a positive numeric, set ",
this is much easier if you  use `paste` not `paste0` as you don't need to remember the weird trailing quoted space

2023-03-29 15:12 UTC, richfitz commented on R/query.R
> +  parsed_expr$type %in% c("latest", "single") ||
What about a single id literal here?

2023-03-29 15:12 UTC, richfitz commented on R/query.R
> +query_parse_usedby <- function(expr, context, subquery_env) {
We are indeed agreeing furiously here, this is fine

2023-03-29 15:12 UTC, richfitz commented on R/query_index.R
> +      if (depth == 0) {
```suggestion
      if (depth <= 0) {
```

Obviously will never happen, but avoids some hard-to-diagnose bugs later when we make a mistake

2023-03-29 15:35 UTC, r-ash commented on R/query.R
> +  parsed_expr$type %in% c("latest", "single") ||
That works atm, see e.g. https://github.com/mrc-ide/outpack/pull/41/files#diff-42bd523386e525f69eae60f196c22a2d79940eae9495f7621647e8b78f493197R725 

`query_parse_usedby` has a switch the first arg to `usedby`. If it is a call, then we parse the call and then validate it using this function. If it is not a call then we just run `query_parse_value`. So the checking for a string ID literal is done in `query_parse_usedby`

2023-03-31 12:29 UTC, richfitz approved these changes

2023-03-31 12:30 UTC, merged