mrc-4109: Add info about subqueries and dependencies into query vignette
mrc-ide/outpack-r pull request #42
Opened 2023-03-21 15:23 UTC by r-ash

2023-03-31 15:16 UTC, richfitz requested changes

2023-03-31 15:16 UTC, richfitz commented on vignettes/query.Rmd
> +outpack_search(quote(usedby({C}) && parameter:year == 2022),
do you want to also talk about the depth argument here too?

2023-03-31 15:16 UTC, richfitz commented on vignettes/query.Rmd
> +### More complex subqueries
I think this section needs expanding. It might be best to fully introduce the orderly use case we discussed as that makes it pretty clear IMO

2023-04-03 16:30 UTC, r-ash commented on vignettes/query.Rmd
> +### More complex subqueries
I've tried to add a use case where we might want this, though not sure if it is the same one we talked about I can't quite remember that so let me know if I have missed the point.

Struggling to contrive an example where we would want to use the `latest({subquery}):name`. Do you have anything in mind? Something where the `subquery` returns an `id` but we don't want that instance of the report, we want the latest version of that ..? Though I don't know why you would do that over just using a search query to return the ID of the packet you do want

2023-04-04 09:13 UTC, richfitz commented on vignettes/query.Rmd
> +### More complex subqueries
I think the example we had was just when we wrote out the orderly yaml and then translated that into subqueries. This will be interesting to think about when we don't have yaml!

Perhaps it's best just to drop this section for now really?

2023-04-04 10:03 UTC, r-ash commented on vignettes/query.Rmd
> +### More complex subqueries
Now gone :)

2023-04-04 10:57 UTC, richfitz approved these changes

2023-04-04 10:57 UTC, merged