Export query deparse function
mrc-ide/outpack-r pull request #48
Opened 2023-04-20 09:53 UTC by r-ash

This PR will
* Rename `query_deparse` to `outpack_query_format` and exports it

I want this in orderly3 to print nice error messages if a query returns no results. This will make #46 obsolete

2023-04-20 11:11 UTC, richfitz requested changes

2023-04-20 11:11 UTC, richfitz commented on R/query_deparse.R
> +  if (length(query) == 1) {
I think that you might keep your original `deparse_query` function here, and then this function (`outpack_query_format`) does some basic validation and passes through:

```
outpack_query_format <- function(query) {
  ok <- is.language(query) || (is.atomic(query) && length(query) == 1)
  if (!ok) {
    stop("unexpected input to....")
  }
  deparse_query(query)
}
```

This will avoid unexpected weird inputs to the API function while keeping the actual deparsing bit focussed, and also has the effect of tidying up the the diff here

2023-04-20 16:35 UTC, r-ash commented on R/query_deparse.R
> +  if (length(query) == 1) {
Thanks! I had a go at this earlier but couldn't work out how to check the `is.atomic`. Fixed this up now

2023-05-02 13:01 UTC, richfitz approved these changes

2023-05-02 13:01 UTC, merged