Support for pulling packets from a location
mrc-ide/outpack-r pull request #5
Opened 2022-03-21 19:32 UTC by richfitz

WIP

2022-03-23 11:45 UTC, r-ash requested changes

2022-03-23 11:45 UTC, r-ash commented on R/location.R
> +  index <- root$index()
`root$index()` returns invisibly - should we drop the `invisible()`? I think a verb function name like `get_index_data` or `update_index`, something which describes what the function does is easier to understand too.

2022-03-23 11:45 UTC, r-ash commented on R/location.R
> +        root$files$get(meta$files$hash[[i]], dest[[i]])
I think I agree with Alex on this one, I also expect `get` to do an assignment to some local variable. I think `copy` is closer to what this actually does.

2022-03-23 11:50 UTC, richfitz commented on R/location.R
> +  index <- root$index()
Definitely we should make it non-invisible.

we just waked back `update_index` in the last PR because that was confusing.  One option would be to make it an "active binding" method  (so that you'd access it like a field `root$index` but that would cause the cache to refresh). Not a huge fan of `get_*` though as that feels like noise.

2022-03-23 11:51 UTC, richfitz commented on R/location.R
> +        root$files$get(meta$files$hash[[i]], dest[[i]])
Can one of you please make a name change in another PR so that we can see the effect of it in isolation please?

2022-03-25 12:04 UTC, hillalex approved these changes
My comments were already addressed in person!

2022-03-25 12:04 UTC, hillalex commented on R/location.R
> +    stop(sprintf("packet '%s' has already been unpacked", id))
can this not just be idempotent (maybe with this as a printed message, just not an error)?

2022-03-25 12:04 UTC, hillalex commented on R/location.R
> +        root$files$get(meta$files$hash[[i]], dest[[i]])
just noticing that "get" feels a bit unclear here, this is actually more like "copy" right?

2022-03-25 12:25 UTC, richfitz commented on R/location.R
> +    stop(sprintf("packet '%s' has already been unpacked", id))
https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3062 - issues around making this idempotent (which I agree should be the behaviour)

2022-03-25 12:28 UTC, richfitz commented on R/location.R
> +        root$files$get(meta$files$hash[[i]], dest[[i]])
Put discussion for that here https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3063

2022-03-25 12:30 UTC, r-ash approved these changes

2022-03-25 12:30 UTC, merged

2022-03-25 12:39 UTC, richfitz commented
> My comments were already addressed in person!

Sorry, wasn't sure where we'd left it. Thanks both :)