Support pulling entire trees
mrc-ide/outpack-r pull request #6
Opened 2022-03-25 10:45 UTC by richfitz

~Merge after #5, as this builds on that PR.~

Support pulling an entire graph - this is the default behaviour of orderly's pull functions. ~It's possible that this would be better done via a `recursive = TRUE` argument to the single packet pull function; would like feedback on this (and not totally sold on the function name either).~ (we have opted to merge, see 18dd804). See comments for other interface questions, most of which can be punted to future work.

~See https://github.com/mrc-ide/outpack/compare/mrc-3029...mrc-3054 for the diff corresponding just to changes here~

2022-03-25 14:55 UTC, r-ash requested changes
Looks great, I think might be worth tightening check on the 2nd `outpack_location_pull_tree` call in the test.

2022-03-25 14:55 UTC, r-ash commented on R/location.R
> +  ## extend outpack_location_pull_packet to allow multiple too?)
I think it will be useful to be able to pull multiple. Especially once exposed in orderly and if we add a way to pull workflows. Can see users wanting to pull multiple reports from orderly and will be nice if outpack supports that already

2022-03-25 14:55 UTC, r-ash commented on tests/testthat/test-location.R
> +  expect_silent(outpack_location_pull_tree(id$c, "src", root = root$dst))
`outpack_location_pull_tree` is always silent? Test passes if you wrap `expect_silent` around call on 398 too. What do we want to test here? That things aren't pulled again? Or more generally that only missing ids are pulled?

2022-03-25 14:55 UTC, r-ash commented on R/location.R
> +outpack_location_pull_tree <- function(id, location, root = NULL) {
Re naming, linking this up with the `outpack_packet_use_dependency` could be nice. `dependency` sets up the tree and then this pulls it. Though `outpack_location_pull_dependencies` doesn't convey recursiveness

2022-03-25 15:02 UTC, richfitz commented on tests/testthat/test-location.R
> +  expect_silent(outpack_location_pull_tree(id$c, "src", root = root$dst))
In contrast to the current behaviour of `outpack_location_pull_packet`, that we allow pulling a tree that has already been pulled, that's all (so this is really expect no error, but the official way of `expect_error(expr, NA)` always confuses me)

2022-03-25 17:34 UTC, richfitz commented on tests/testthat/test-location.R
> +  expect_silent(outpack_location_pull_tree(id$c, "src", root = root$dst))
OK, we now return a vector of updated ids (invisibly) which makes the testing more explicit and I think is a reasonable interface in the absence of decent logging

2022-03-25 17:34 UTC, richfitz commented on R/location.R
> +  ## extend outpack_location_pull_packet to allow multiple too?)
I've combined things as discussed so this is now addressed

2022-03-25 17:36 UTC, richfitz commented
Following from @r-ash's review (and our chat) it felt like combining the two together makes sense, so I've reworked this so that `outpack_location_pull_packet` takes a `recursive` argument. This is actually then something that later we could set the default for in the configuration perhaps as some repos will want to be complete by default. I've shuffled around the comments which refer to work that needs doing later

2022-03-28 09:28 UTC, r-ash approved these changes

2022-03-28 09:54 UTC, hillalex commented on R/graph.R
> +find_all_dependencies <- function(id, metadata) {
No unit tests for this? The added test checks `a -> b -> c` can be resolved, but doesn't test other cases e.g. case where `id`  has length > 1, multiple dependencies at top or nested levels of the chain...

2022-03-28 10:29 UTC, richfitz commented on R/graph.R
> +find_all_dependencies <- function(id, metadata) {
Was being lazy due to expecting this to change a bunch and being pretty braindead. I've added some tests in e0143fb

2022-03-28 10:43 UTC, hillalex commented on R/graph.R
> +find_all_dependencies <- function(id, metadata) {
Nice, thanks :)

2022-03-28 10:43 UTC, hillalex approved these changes

2022-03-28 10:44 UTC, merged