Add test that checks behaviour when searching for boolean type parameters
mrc-ide/outpack-r pull request #74
Opened 2023-06-26 13:20 UTC by r-ash

This PR just adds a test that checks explicitly the behaviour of querying for boolean types. I couldn't see an existing one and wanted this as a reference for writing the rust impl

2023-06-26 14:47 UTC, r-ash commented on tests/testthat/test-query-search.R
> +    c(x1, y1))
Is this the actual behaviour we want? Or do we want to tighten the querying here?

This is a bit fiddly to sort out in the Rust querying but we could do it. Alternative is we can make the querying here in R care about types. E.g. not return `x1` when querying for `"TRUE"` and not return `y1` when querying for `TRUE`

2023-06-26 15:01 UTC, richfitz requested changes

2023-06-26 15:01 UTC, richfitz commented on tests/testthat/test-query-search.R
> +    c(x1, y1))
I don't think this is what we want - could you fix it? Ideally `==` would do no type coercion except between int and double

2023-07-20 13:40 UTC, r-ash commented
Fixed in orderly2!

2023-07-20 13:40 UTC, closed without merging