Add query describing the metadata format
mrc-ide/outpack-r pull request #77
Opened 2023-06-28 07:07 UTC by richfitz

As discussed, this starts some docs on what is going on with all the little files everywhere

2023-06-28 14:08 UTC, r-ash requested changes
Looks great, would be useful to also add a few comments about when metadata, location info get written to and what they are used for

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +Each "packet" was conceptually a directory, corresponding to a particular analysis or data product, though this is not necessarily how it is stored. The internal representation includes:
```suggestion
Each "packet" is conceptually a directory, corresponding to a particular analysis or data product, though this is not necessarily how it is stored. The internal representation includes:
```
?

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +We will need to distinguish between packets which are "unpacked" (that is, packets with every file available in the current archive) and packets that are merely known about (those for which we have t
Do we want to talk about packets which are "local" instead of "unpacked" or still useful to use that terminology?

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +## Packet metadata (`.outpack/metadata/`)
These get created when we either run a packet locally, or when we pull a packet, or dependencies of a packet?

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +This directory matches the regular expression `^[0-9]{8}$` (e.g., `457f4f2a`) and is a "location id" (see below) corresponding to a "location". Each file within this directory has an outpack id as na
Does one of these represent the local location? When do we get this information?

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +With `<name>` being the "name" of the packet, `<id>` being its outpack id.  There will be several files per packet, possibly themselves in directories. This storage approach is designed to be human r
Incomplete sentence here

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +In order to make a packet available from a location, you need to import the metadata and the files
What does having a packet available enable us to do? Use it as a dependency? Anything else?

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +## Packet metadata (`.outpack/metadata/`)
Bit of crossover with section below about "Adding metadata"

2023-06-28 14:08 UTC, r-ash commented on vignettes/metadata.Rmd
> +This directory matches the regular expression `^[0-9]{8}$` (e.g., `457f4f2a`) and is a "location id" (see below) corresponding to a "location". Each file within this directory has an outpack id as na
Ah actually below looks like local location info is at `outpack/<local location id>`

2023-06-28 17:13 UTC, richfitz commented
> Looks great, would be useful to also add a few comments about when metadata, location info get written to and what they are used for

Could you expand on what you are thinking here?

2023-06-28 17:15 UTC, richfitz commented on vignettes/metadata.Rmd
> +We will need to distinguish between packets which are "unpacked" (that is, packets with every file available in the current archive) and packets that are merely known about (those for which we have t
I've added a comment on this now

2023-06-28 17:15 UTC, richfitz commented on vignettes/metadata.Rmd
> +## Packet metadata (`.outpack/metadata/`)
yeah, good spots. Clarified the first one and removed duplication on the second

2023-06-28 17:16 UTC, richfitz commented on vignettes/metadata.Rmd
> +This directory matches the regular expression `^[0-9]{8}$` (e.g., `457f4f2a`) and is a "location id" (see below) corresponding to a "location". Each file within this directory has an outpack id as na
yeah, I've added a comment on this to make that clearer.

2023-06-28 17:16 UTC, richfitz commented on vignettes/metadata.Rmd
> +With `<name>` being the "name" of the packet, `<id>` being its outpack id.  There will be several files per packet, possibly themselves in directories. This storage approach is designed to be human r
fixed now

2023-06-28 17:16 UTC, richfitz commented on vignettes/metadata.Rmd
> +With `<name>` being the "name" of the packet, `<id>` being its outpack id.  There will be several files per packet, possibly themselves in directories. This storage approach is designed to be human r
fixed now

2023-06-30 16:10 UTC, r-ash commented
> > Looks great, would be useful to also add a few comments about when metadata, location info get written to and what they are used for
> 
> Could you expand on what you are thinking here?

Was thinking things like metadata and local location get written to when a packet run is complete `outpack_packet_end`. Metadata also written when we pull `outpack_location_pull_metadata` or when we pull a packet `outpack_location_pull_packet` (I think). We write to location metadata on `outpack_location_pull_metadata`

And when we use this metadata and location information. We use metadata to use another packet as a dependency `outpack_packet_use_dependency`. But not sure actually what functions use the location info? Maybe just exists as a record instead of being something we use somewhere?

2023-06-30 16:10 UTC, r-ash approved these changes
Looks great!

2023-07-11 08:06 UTC, merged